### ISSUE TITLE
运行过程中出现错误

### ISSUE THREAD

**Issue by ylot0** [liuwons/wxBot#131]
systems:ubuntu14.04LTS
python:  python2.7

[MSG] 80B雪儿:
    [Text] [尴尬]
    ROBOT: 啊喔，怎么了？
[ERROR] Except in proc_msg
Traceback (most recent call last):
  File "/home/wlp2s0/wxBot-master/wxbot.py", line 618, in proc_msg
    self.handle_msg(r)
  File "/home/wlp2s0/wxBot-master/wxbot.py", line 594, in handle_msg
    self.handle_msg_all(message)
  File "bot.py", line 69, in handle_msg_all
    self.send_msg_by_uid(self.tuling_auto_reply(msg['user']['id'], msg['content']['data']), msg['user']['id'])
  File "/home/wlp2s0/wxBot-master/wxbot.py", line 792, in send_msg_by_uid
    dic = r.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ylot0** [comment]
[MSG] 张婷婷:
    [Text] 你的内裤干不了
    ROBOT: 在这样我就不喜欢你了哦
[ERROR] Except in proc_msg
Traceback (most recent call last):
  File "/home/wlp2s0/wxBot-master/wxbot.py", line 618, in proc_msg
    self.handle_msg(r)
  File "/home/wlp2s0/wxBot-master/wxbot.py", line 594, in handle_msg
    self.handle_msg_all(message)
  File "bot.py", line 72, in handle_msg_all
    my_names = self.get_group_member_name(self.my_account['UserName'], msg['user']['id'])
  File "/home/wlp2s0/wxBot-master/wxbot.py", line 792, in send_msg_by_uid
    except (ConnectionError, ReadTimeout):
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by huangguozhen** [comment]
这个问题解决了吗?
