### ISSUE TITLE
无法运行no attribute 'encoding'

### ISSUE THREAD

**Issue by nightest** [liuwons/wxBot#157]
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    main()
  File "test.py", line 24, in main
    bot.run()
  File ".../wxbot.py", line 969, in run
    self.get_uuid()
  File "../wxbot.py", line 1005, in get_uuid
    r.encoding = 'utf-8'
AttributeError: 'NoneType' object has no attribute 'encoding'

test.py与bot.py均报错，如上所示

**Comment by nightest** [comment]
已经解决， 原因是长时间等待网络连接，没有获得数据。使用代理即可解决问题，或者更换网络。
