### ISSUE TITLE
'ascii' codec can't decode byte 0xc8 in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by cndlan** [liuwons/wxBot#159]
'ascii' codec can't decode byte 0xc8 in position 1: ordinal not in range(128)

现在报这个错

**Comment by xmcp** [comment]
你能提供下完整traceback吗？

**Comment by cndlan** [comment]
[MSG] unknown:
[ERROR] Except in proc_msg
Traceback (most recent call last):
  File "F:\Ⱥ���\wxBot-master��ɰ�\wxbot.py", line 619, in proc_msg
    self.handle_msg(r)
  File "F:\Ⱥ���\wxBot-master��ɰ�\wxbot.py", line 589, in handle_msg
    content = self.extract_msg_content(msg_type_id, msg)
  File "F:\Ⱥ���\wxBot-master��ɰ�\wxbot.py", line 443, in extract_msg_content
    image = self.get_msg_img(msg_id)
  File "F:\Ⱥ���\wxBot-master��ɰ�\wxbot.py", line 1237, in get_msg_img
    with open(os.path.join(self.temp_pwd,fn), 'wb') as f:
  File "C:\Python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 1: ordinal not in range(128)

**Comment by xmcp** [comment]
上Python3，或者在目录里面别出现中文
