### ISSUE TITLE
'Connection aborted.', BadStatusLine("''",)

### ISSUE THREAD

**Issue by ruxi-xsw** [liuwons/wxBot#229]
最近发现机器人总是出现下面错误，重启也没有效果。。

```python
('Connection aborted.', BadStatusLine("''",)) Traceback (most recent call last):
  File "C:\Users\xsw\Workspaces\python\HTSecBot\wxbot.py", line 53, in request
    allow_redirects, proxies, hooks, stream, verify, cert, json)
  File "C:\python\Python27\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\python\Python27\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\python\Python27\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by eastossifrage** [comment]
在ubuntu下,安装下面的插件,会管用.
```bash
sudo apt-get install libfontconfig
```

windows下,就不明白了.

**Comment by xmcp** [comment]
@eastossifrage `libfontconfig`应该跟这个异常没关系

**Comment by lishuoxi** [comment]
同样的错误, 这两天运行会自己关掉., 不知道是什么问题, 头疼
