### ISSUE TITLE
ImportError: No module named pyqrcode

### ISSUE THREAD

**Issue by zhanggaoxuan** [liuwons/wxBot#249]
执行测试脚本时候遇到的问题= =

[root@centos1 wxBot]# python test.py                                            
Traceback (most recent call last):                                              
  File "test.py", line 5, in <module>                                           
    from wxbot import *                                                         
  File "/root/wxBot/wxbot.py", line 8, in <module>                              
    import pyqrcode                                                             
ImportError: No module named pyqrcode                                           
[root@centos1 wxBot]# python wxbot.py                                           
Traceback (most recent call last):                                              
  File "wxbot.py", line 8, in <module>                                          
    import pyqrcode                                                             
ImportError: No module named pyqrcode

**Comment by kinggggg** [comment]
我的macOS上也遇到同样的问题，如何解决？

**Comment by Geno1024** [comment]
没有 pyqrcode 就安装它……README 已经有写了……
