### ISSUE TITLE
有错误，user)id属性找不到

### ISSUE THREAD

**Issue by Blacker13** [liuwons/wxBot#4]
`[INFO] Start to process messages .
Traceback (most recent call last):
  File "D:\Temp\workspace\pythonTest\src\com\dscao\test1\weixin.py", line 20, in <module>
    main()
  File "D:\Temp\workspace\pythonTest\src\com\dscao\test1\weixin.py", line 17, in main
    bot.run()
  File "D:\Temp\workspace\pythonTest\src\com\dscao\test1\wxbot.py", line 545, in run
    self.proc_msg()
  File "D:\Temp\workspace\pythonTest\src\com\dscao\test1\wxbot.py", line 457, in proc_msg
    self.schedule()
  File "D:\Temp\workspace\pythonTest\src\com\dscao\test1\weixin.py", line 11, in schedule
    self.send_msg('tb', 'schedule')
  File "D:\Temp\workspace\pythonTest\src\com\dscao\test1\wxbot.py", line 488, in send_msg
    uid = self.get_user_id(name)
AttributeError: MyWXBot instance has no attribute 'get_user_id'`

**Comment by liuwons** [comment]
刚看了下，是get_user_id函数没有实现，你git下载下新代码试试？
