### ISSUE TITLE
test.py可正常运行，但修改hi为中文后就不行了

### ISSUE THREAD

**Issue by xu-xiang** [liuwons/wxBot#45]
如题
修改中文后，用其它账户发送消息给我扫码登录的账户就是：
[INFO] Please use WeChat to scan the QR code .
[INFO] Please confirm to login .
[INFO] Web WeChat login succeed .
[INFO] Web WeChat init succeed .
[INFO] Get 176 contacts
[INFO] Start to process messages .
[MSG] *******:
    [Text] 归
Traceback (most recent call last):
  File "test_1.py", line 28, in <module>
    main()
  File "test_1.py", line 24, in main
    bot.run()
  File "/git/my/wxBot/wxbot.py", line 718, in run
    self.proc_msg()
  File "/git/my/wxBot/wxbot.py", line 605, in proc_msg
    self.handle_msg(r)
  File "/git/my/wxBot/wxbot.py", line 581, in handle_msg
    self.handle_msg_all(message)
  File "test_1.py", line 10, in handle_msg_all
    self.send_msg_by_uid('哈哈', msg['user']['id'])
  File "/git/my/wxBot/wxbot.py", line 636, in send_msg_by_uid
    data = json.dumps(params, ensure_ascii=False).encode('utf8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1: ordinal not in range(128)

**Comment by liuwons** [comment]
同#46，请用 unicode 字符串，例如 ```self.send_msg(u'张三', u'测试')```
