### ISSUE TITLE
win 10 下运行不了

### ISSUE THREAD

**Issue by ixiusama** [liuwons/wxBot#50]
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from wxbot import *
  File "C:\Users\XXXX\Desktop\wxBot-0.1\wxbot.py", line 285
    print '    %s[Location] %s ' % (msg_prefix, pos)
```

**Comment by ixiusama** [comment]
python 3.5

**Comment by ixiusama** [comment]
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from wxbot import *
  File "C:\Users\xiaoyue\Desktop\wxBot-python3\wxbot.py", line 623
    print '[ERROR] Login failed due to network problem, please try again.'
                                                                         ^
SyntaxError: Missing parentheses in call to 'print'
```
提问的第一个错误返回是releases的
这个错误返回是wxBot-python3 的分支的.

**Comment by xmcp** [comment]
这跟win10没关系，就是python3分支里没在print两边加括号

**Comment by ixiusama** [comment]
什么括号 中括号还是普通括号

**Comment by ixiusama** [comment]
ok,那就反应个bug 吧
wxbot.py
623行应修改为
`            print ('[ERROR] Login failed due to network problem, please try again.')`
bot.py
42行应该为
`            print ('    ROBOT:', result)`
这种就不分支推送了.
