### ISSUE TITLE
会莫名其妙的死掉

### ISSUE THREAD

**Issue by ixiusama** [liuwons/wxBot#54]
```
Traceback (most recent call last):
  File "bot.py", line 118, in <module>
    main()
  File "bot.py", line 114, in main
    bot.run()
  File "C:\Users\XXXXX\Desktop\wxBot-python3\wxbot.py", line 561, in run
    self.proc_msg()
  File "C:\Users\XXXXX\Desktop\wxBot-python3\wxbot.py", line 466, in proc_msg
    time.sleep(0.5 - check_time)
KeyboardInterrupt
```

**Comment by ixiusama** [comment]
突然性的卡掉，一直不动 有时候又会突然可以运行有时候就会爆出上面的错误代码。

**Comment by xmcp** [comment]
你是不是按ctrl-C了

**Comment by ixiusama** [comment]
是卡死了之后才按 ctrl-c的 然后爆这个错

**Comment by ixiusama** [comment]
感觉是网络超时了？？

**Comment by xmcp** [comment]
明明是卡在time.sleep了呀……你试试print一下延时的时间，不过我觉得是不是没有卡、只是死循环了？

**Comment by ixiusama** [comment]
讲道理要怎么写？？我~我~我~不会呀？求教？

**Comment by liuwons** [comment]
最近尝试修复了此问题: [commit](https://github.com/liuwons/wxBot/commit/8a1b30666398feb5c735b0e6295ec1d3800141ba)

在我的机子上运行了一天没出现卡死的情况，更新下看看有没有解决问题 @ixiusama

**Comment by liuwons** [comment]
如果新版本还有次问题请重开此issue

**Comment by ixiusama** [comment]
Traceback (most recent call last):
  File "C:\Users\XXXXXX\Desktop\wxBot-master\bot.py", line 102, in <module>
    main()
  File "C:\Users\XXXXXX\Desktop\wxBot-master\bot.py", line 98, in main
    bot.run()
  File "C:\Users\XXXXXX\Desktop\wxBot-master\wxbot.py", line 743, in run
    if self.init():
  File "C:\Users\XXXXXX\Desktop\wxBot-master\wxbot.py", line 873, in init

    r = self.session.post(url, data=json.dumps(params))
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(10054, ''))
报错？？？~

**Comment by liuwons** [comment]
@ixiusama 这好像是网络连接错误，每次运行都这样吗？

**Comment by xmcp** [comment]
10054指的是`[WinError 10054] 远程主机强迫关闭了一个现有的连接。`，就是说微信服务器不知道因为什么，结束了你的TCP连接

**Comment by ixiusama** [comment]
应该是我新开的一个号没有设置微信的那个 「微信号」所以会有这种问题，设置了之后运行了一天，没有问题。
