### ISSUE TITLE
[bug] Except in proc_msg

### ISSUE THREAD

**Issue by liuyang007** [liuwons/wxBot#66]
[ERROR] Except in proc_msg
```
Traceback (most recent call last):
  File "/home/liuyang/wall/weixin/wxbot2/lib/wxbot.py", line 613, in proc_msg
    self.handle_msg(r)
  File "/home/liuyang/wall/weixin/wxbot2/lib/wxbot.py", line 583, in handle_msg
    content = self.extract_msg_content(msg_type_id, msg)
  File "/home/liuyang/wall/weixin/wxbot2/lib/wxbot.py", line 416, in extract_msg_content
    name = self.get_group_member_prefer_name(self.get_group_member_name(uid, msg['FromUserName']))
TypeError: get_group_member_name() takes exactly 2 arguments (3 given)
```

**Comment by beader** [comment]
`get_group_member_name` 这个函数在 wxbot.py 中重复定义了。将`bot.py`例子中的

```python
my_names = self.get_group_member_name(self.my_account['UserName'], msg['user']['id'])
```
替换为
```python
my_names = self.get_group_member_name(self.my_account['UserName'])
```

后即可正常使用。
