### ISSUE TITLE
ImportError: No module named png

### ISSUE THREAD

**Issue by fanzai1hao** [liuwons/wxBot#79]
Traceback (most recent call last):
  File "F:/hufan/test.py", line 28, in <module>
    main()
  File "F:/hufan/test.py", line 24, in main
    bot.run()
  File "F:\hufan\wxbot.py", line 709, in run
    self.gen_qr_code('qr.png')
  File "F:\hufan\wxbot.py", line 757, in gen_qr_code
    qr.png(qr_file_path, scale=8)
  File "build\bdist.win-amd64\egg\pyqrcode\__init__.py", line 464, in png
    
  File "build\bdist.win-amd64\egg\pyqrcode\builder.py", line 1266, in _png
ImportError: No module named png

Process finished with exit code 1

运行test.py显示没有png模块，这是怎么回事？？？求解答啊啊啊啊

**Comment by xmcp** [comment]
`pip install pypng`

**Comment by shethshaurya** [comment]
try writing import png instead of import pypng. it works
